import Head from 'next/head'
import { useContext } from 'react'
import AppContext from '../context'

export default function Home() {
  const { state } = useContext(AppContext)

  return (
    <div>
      <Head>
        <title>Next Js is Fun!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello World. {state.theme}</h1>
      </main>

      <footer>
        This will be my footer
      </footer>
    </div>
  )
}
