import Head from 'next/head'
import { useContext, useEffect, useState } from 'react'
import { Container, Row } from 'react-bootstrap'
import AppContext from '../context'
import TypingText from '../components/typingText'
import Clock from '../components/clock'

export default function Home() {
  const { darkModeBg, state, delay } = useContext(AppContext)
  const [isGreet, setIsGreet] = useState(false)

  // COMPUTED
  const greeting = () => state.theme === 'light' ? 'GOOD DAY!' : 'GOOD EVENING!'

  useEffect(() => {
    (async () => {
      await delay(5000)
      setIsGreet(true);
    })()
  }, [])

  return (
    <div>
      <Head>
        <title>Next Js is Fun!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={darkModeBg()}>
        <Container className="vh-100 d-flex flex-column justify-content-center align-items-center">
          <Row>
            <Clock />
          </Row>
          <Row>
            <TypingText>Hello World!</TypingText>
          </Row>
          <Row>
            <TypingText delay={1000} component="p">My name is dhoni</TypingText>
          </Row>
          <Row>
            <TypingText delay={2000} component="h3">Resolving inquiries by using tech...</TypingText>
          </Row>
          <Row>
            <h2>{isGreet && greeting()}</h2>
          </Row>
        </Container>
      </main>
    </div>
  )
}
